### PR TITLE
Update Hive-Avro-To-ORC-Converter.md for typos

### PR DESCRIPTION
**Pull request by bstaudacher**
Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/projects/GOBBLIN/issues/GOBBLIN-931?filter=allopenissues) issues and references them in the PR title.
    - https://issues.apache.org/jira/projects/GOBBLIN/issues/GOBBLIN-931?filter=allopenissues

### Description
- [X] Here are some details about my PR, including screenshots (if applicable):

The following typos are amended:
registred  -> registered
converison  -> conversion

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Just a typo fix

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by jhsenjaliya** [comment]
LGTM,
@bstaudacher do you want to just run the spell check on all docs and fix it ? 
Also pls create JIRA ticket and mention that here.
Thanks

**Comment by bstaudacher** [comment]
I don't believe I can make a JIRA ticket, I went and poked around but it appears I don't have the option to do so.

**Comment by jhsenjaliya** [comment]
Thanks @autumnust for creating the ticket for @bstaudacher . Should we make this generic Typo fixer ticket ? that would help improve the docs. what do you think?

**Comment by bstaudacher** [comment]
I would say LGTM and then I can take a look at programatically fixing the rest of the typos that may exist in the docs? Or if you prefer to have this ticket be a catch all we could go that route as well.

**Comment by autumnust** [comment]
@bstaudacher  Just out of curiosity: Which tool are you planning to address typos given the scale of this code base? I am more than happy to assist on that if you already have a plan. 

I updated https://issues.apache.org/jira/browse/GOBBLIN-931 to be not specific to Avro-to-ORC.

**Comment by bstaudacher** [comment]
@autumnust I was looking to utilize [aspell](http://aspell.net/).
A good guide on basic usage can be found here:
https://alexwlchan.net/2016/09/please-use-aspell

The only consideration that stands out to me would be how to easily compile a list of exceptions (Avro, ORC etc.) to place in the `~/.aspell.lang.pws` file.

Thoughts?

**Comment by autumnust** [comment]
> @autumnust I was looking to utilize [aspell](http://aspell.net/).
> A good guide on basic usage can be found here:
> https://alexwlchan.net/2016/09/please-use-aspell
> 
> The only consideration that stands out to me would be how to easily compile a list of exceptions (Avro, ORC etc.) to place in the `~/.aspell.lang.pws` file.
> 
> Thoughts?

I am assuming all these binary files are named in a specific way (.avro for example). I would be interested to know how much Avro/ORC files sit in the repo since we really should just get rid of them by replacing with .json and deserialize in memory when necessary.

**Comment by bstaudacher** [comment]
Ahhh the binary files won't be a problem, when we glob over them we can exclude anything save the `.md`'s we wish to spellcheck. Moreso I am wondering about how we can compile a list of spellcheck exceptions so that aspell doesn't blow up on the project specific jargon like "Avro".

There might not be a nice way to do that programatically, luckily because aspell spits out .bak files we could diff and then gain a quick understanding by eye of common terms that are being flagged.

**Comment by autumnust** [comment]
> Ahhh the binary files won't be a problem, when we glob over them we can exclude anything save the `.md`'s we wish to spellcheck. Moreso I am wondering about how we can compile a list of spellcheck exceptions so that aspell doesn't blow up on the project specific jargon like "Avro".
> 
> There might not be a nice way to do that programatically, luckily because aspell spits out .bak files we could diff and then gain a quick understanding by eye of common terms that are being flagged.

Ah I misunderstood. I am not familiar with aspell and quickly googled it and seems there's no support for blacklist type of thing.

**Pull request merged**
