### PR TITLE
[GOBBLIN-1631]Emit heartbeat for dagManagerThread

### PR DESCRIPTION
**Pull request by ZihanLi58**
Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1631

### Description
- [ ] Here are some details about my PR, including screenshots (if applicable):
Heartbeat corresponds to one cycle of DAG manager thread (when it reaches cleanup phase). We want one metric per thread so we can tell which thread is dead/alive. Use thread id in metric name.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Review by Will-Lo — APPROVED** [review]

**Comment by Will-Lo** [comment]
FYI there's some old commits in this branch, could you clean by rebasing or cherry-picking the commit to latest master?

**Comment by ZihanLi58** [comment]
> FYI there's some old commits in this branch, could you clean by rebasing or cherry-picking the commit to latest master?

I did rebase it so the file diff only contains change I make this time, but somehow the commit history is still there

**Comment by linweihs** [comment]
in https://issues.apache.org/jira/browse/GOBBLIN-1631 : We want one metric per thread so we can tell which thread is dead/alive. 

On what cases the thread would be considered dead ? lets say if one thread processing and encounter exception, is that considered as dead in this case? if so, what other use cases can a thread be dead ? 

also, do you think it be helpful to add additional instrument metrics such as Dags in / out  throughput to know if Dags is processing everything without backlog

**Comment by ZihanLi58** [comment]
> in https://issues.apache.org/jira/browse/GOBBLIN-1631 : We want one metric per thread so we can tell which thread is dead/alive.
> 
> On what cases the thread would be considered dead ? lets say if one thread processing and encounter exception, is that considered as dead in this case? if so, what other use cases can a thread be dead ?
> 
> also, do you think it be helpful to add additional instrument metrics such as Dags in / out throughput to know if Dags is processing everything without backlog

1. If the dag manager thread always hit some exception during processing or if the thread itself never get resources to run and cannot hit the cleanDag stage for a long time, we consider it as dead.  From monitoring side, if the heartbeat metric is 0 for a  time, we can consider it as dead.
2. Yes, we can also add that if needed, just add one guage to report the total size of the dag queues should be enough for you to monitor if there is any backlog, but kind of out the scope of this PR.

**Pull request merged**
