### PR TITLE
[GOBBLIN-1498] add a few metrics in GaaS to help debug point of failure

### PR DESCRIPTION
**Pull request by arjun4084346**
Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!
@Will-Lo @umustafi please review

### JIRA
- [x] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1498

### Description
- [x] Here are some details about my PR, including screenshots (if applicable):
This PR will add meter metrics for a) running scheduled, b) nonscheduled flows, c) flows execution is skipped, d) add/update/delete/cancel flow specs sent by SimpleKafkaSpecProducer

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
trivial changes

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Review by umustafi — APPROVED** [review]
Looks good. All the meters I'm seeing are not flow specific, so they give us an idea of the quantity of flows that are failing/successful/scheduled/etc... but not which flows right? We often then have to look into which flows are failing/skipped from logs and debug when we have issues. Is there a reasonable way we can also keep track of flow name and status for logging?

**Review by Will-Lo — APPROVED** [review]

**Comment by Will-Lo** [comment]
@umustafi agreed, would be good if we could tag the metrics somehow to have them filterable by flow, would be good for monitoring purposes.

**Comment by arjun4084346** [comment]
@umustafi @Will-Lo  we have a few metrics for each flow, e.g. flow pass/fail, compilation pass/fail. Because there are too many flows in total, I am not sure if we want to add each detailed metrics for each flow.

**Comment by arjun4084346** [comment]
@sv2000  please review/merge

**Review by sv2000 — APPROVED** [review]
+1.

**Pull request merged**
